version: '3'
services:
  mypostgres:
    image: "postgres"
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/db
    environment:
     - POSTGRES_PASSWORD=123456
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres

volumes:
    pgdata:
      driver: local