version: '2'

services:
  clinic_ca:
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.clinic.carewallet.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/66766ca44b6b5185418dbf57170fd33726a0466b94c29b4211518bf5f498fe6b_sk -b admin:adminpw ${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.clinic.carewallet.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/66766ca44b6b5185418dbf57170fd33726a0466b94c29b4211518bf5f498fe6b_sk -d'
    volumes:
      - ./crypto-config/peerOrganizations/clinic.carewallet.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    container_name: clinic_ca

  human_ca:
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.human.carewallet.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3b44f91ca7ee697e47e963fb739a1c48c39b47b152ec6229b7a95b843c43b0f3_sk -b admin:adminpw ${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.human.carewallet.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/3b44f91ca7ee697e47e963fb739a1c48c39b47b152ec6229b7a95b843c43b0f3_sk -d'
    volumes:
      - ./crypto-config/peerOrganizations/human.carewallet.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    container_name: human_ca

  insurance_ca:
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurance.carewallet.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4e7531dfac6eff58591750836c2d75ca0d131a8ea8a6bf8dd9166cde08b7fb1c_sk -b admin:adminpw ${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurance.carewallet.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/4e7531dfac6eff58591750836c2d75ca0d131a8ea8a6bf8dd9166cde08b7fb1c_sk -d'
    volumes:
      - ./crypto-config/peerOrganizations/insurance.carewallet.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    container_name: insurance_ca

  orderer.carewallet.com:
    container_name: orderer.carewallet.com
    image: hyperledger/fabric-orderer${IMAGE_TAG_FABRIC}
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_TLS}
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
#      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt, /etc/hyperledger/msp/peer0Org1/tls/ca.crt, /etc/hyperledger/msp/peer1Org1/tls/ca.crt, /etc/hyperledger/msp/peer0Org2/tls/ca.crt, /etc/hyperledger/msp/peer1Org2/tls/ca.crt]
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
     - ./channel-artifacts:/etc/hyperledger/configtx:ro
     - ./crypto-config/ordererOrganizations/carewallet.com/orderers/orderer.carewallet.com/:/etc/hyperledger/msp/orderer:ro
    ports:
      - 7050:7050

  peer0.clinic.carewallet.com:
    container_name: peer0.clinic.carewallet.com
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.clinic.carewallet.com
      - CORE_PEER_ADDRESS=peer0.clinic.carewallet.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.clinic.carewallet.com:7051
#      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=ClinicMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_clinic:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./channel-artifacts:/etc/hyperledger/configtx:ro
      - ./crypto-config/peerOrganizations/clinic.carewallet.com/peers/peer0.clinic.carewallet.com/:/etc/hyperledger/msp/peer:ro
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.carewallet.com
      - couchdb_clinic

  peer0.human.carewallet.com:
    container_name: peer0.human.carewallet.com
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.human.carewallet.com
      - CORE_PEER_ADDRESS=peer0.human.carewallet.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.human.carewallet.com:8051
#      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=HumanMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_human:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/human.carewallet.com/peers/peer0.human.carewallet.com/:/etc/hyperledger/msp/peer:ro
      - ./channel-artifacts:/etc/hyperledger/configtx:ro
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer.carewallet.com
      - couchdb_human

  peer0.insurance.carewallet.com:
    container_name: peer0.insurance.carewallet.com
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.carewallet.com
      - CORE_PEER_ADDRESS=peer0.insurance.carewallet.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.carewallet.com:9051
#      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_insurance:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/insurance.carewallet.com/peers/peer0.insurance.carewallet.com/:/etc/hyperledger/msp/peer:ro
      - ./channel-artifacts:/etc/hyperledger/configtx:ro
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer.carewallet.com
      - couchdb_insurance

  ccenv:
    image: hyperledger/fabric-ccenv${IMAGE_TAG_FABRIC}

  couchdb_clinic:
    container_name: couchdb_clinic
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC}
    ports:
      - 7984:5984

  couchdb_human:
    container_name: couchdb_human
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC}
    ports:
      - 8984:5984

  couchdb_insurance:
    container_name: couchdb_insurance
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC}
    ports:
      - 9984:5984