#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ca.health.com:
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.health.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.clinic.health.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/88f166b5ba6dfddec0c7edbb4c406d456aca57a6bbe67e504afe708613937f3f_sk -b admin:adminpw ${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.clinic.health.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/88f166b5ba6dfddec0c7edbb4c406d456aca57a6bbe67e504afe708613937f3f_sk -d'
    volumes:
      - ./crypto-config/peerOrganizations/clinic.health.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.health.com
    networks:
      - basic

  orderer.health.com:
    container_name: orderer.health.com
    image: hyperledger/fabric-orderer${IMAGE_TAG_FABRIC}
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_TLS}
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
#      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt, /etc/hyperledger/msp/peer0Org1/tls/ca.crt, /etc/hyperledger/msp/peer1Org1/tls/ca.crt, /etc/hyperledger/msp/peer0Org2/tls/ca.crt, /etc/hyperledger/msp/peer1Org2/tls/ca.crt]
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./config:/etc/hyperledger/configtx:ro
      - ./crypto-config/ordererOrganizations/health.com/orderers/orderer.health.com/:/etc/hyperledger/msp/orderer:ro
    ports:
      - 7050:7050
    networks:
      - basic

  peer0.clinic.health.com:
    container_name: peer0.clinic.health.com
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.clinic.health.com
      - CORE_PEER_ADDRESS=peer0.clinic.health.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.clinic.health.com:7051
#      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=ClinicMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/clinic.health.com/peers/peer0.clinic.health.com/:/etc/hyperledger/msp/peer:ro
      - ./config:/etc/hyperledger/configtx:ro
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.health.com
      - couchdb1
    networks:
      - basic

  peer1.clinic.health.com:
    container_name: peer1.clinic.health.com
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.clinic.health.com
      - CORE_PEER_ADDRESS=peer1.clinic.health.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.clinic.health.com:8051
#      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=ClinicMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/clinic.health.com/peers/peer1.clinic.health.com/:/etc/hyperledger/msp/peer:ro
      - ./config:/etc/hyperledger/configtx:ro
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer.health.com
      - couchdb2
    networks:
      - basic

  peer2.clinic.health.com:
    container_name: peer2.clinic.health.com
    extends:
      file: peer-base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.clinic.health.com
      - CORE_PEER_ADDRESS=peer2.clinic.health.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.clinic.health.com:9051
#      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=ClinicMSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/clinic.health.com/peers/peer2.clinic.health.com/:/etc/hyperledger/msp/peer:ro
      - ./config:/etc/hyperledger/configtx:ro
    ports:
      - 9051:7051
      - 9053:7053
    depends_on:
      - orderer.health.com
      - couchdb3
    networks:
      - basic

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC}
    ports:
      - 5984:5984
    networks:
      - basic
      
  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC}
    ports:
      - 6984:5984
    networks:
      - basic
      
  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb${IMAGE_TAG_FABRIC}
    ports:
      - 7984:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.clinic.health.com:7051
      - CORE_PEER_LOCALMSPID=clinicMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/clinic.health.com/users/Admin@clinic.health.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
      - basic
    depends_on:
      - orderer.health.com
      - peer0.clinic.health.com
      - couchdb1
